# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 22:45
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('data', jsonfield.fields.JSONField(default=dict)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=20, populate_from='name', unique=True)),
                ('data', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=20, populate_from='name', unique_with=['course'])),
                ('order', models.PositiveSmallIntegerField()),
                ('data', jsonfield.fields.JSONField(default=dict)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slides.Course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=20, populate_from='title', unique_with=['deck'])),
                ('order', models.PositiveSmallIntegerField()),
                ('content', models.TextField()),
                ('data', jsonfield.fields.JSONField(default=dict)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slides.Deck')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_touch', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', jsonfield.fields.JSONField(default=dict)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slides.Course')),
                ('current_slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slides.Slide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='annotation',
            name='slide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slides.Slide'),
        ),
        migrations.AlterUniqueTogether(
            name='slide',
            unique_together=set([('deck', 'order')]),
        ),
        migrations.AlterUniqueTogether(
            name='deck',
            unique_together=set([('course', 'order')]),
        ),
        migrations.AlterUniqueTogether(
            name='annotation',
            unique_together=set([('slide', 'order')]),
        ),
    ]
