# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('D', 'Deleted')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='deck',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('D', 'Deleted')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='slide',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('D', 'Deleted')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='slide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='slides.Slide'),
        ),
    ]
